name: Daily Update

on:
  schedule:
    - cron: '*/3 * * * *'  # This cron expression runs the workflow every day at 5 PM IST 

jobs:
  update_and_download:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file_name: [daily_current_affairs_links.csv]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 openpyxl

    - name: Run Python script
      run: python Current_Affairs_Daily_Links_Update.py
      working-directory: .  # Set the working directory to the repository root

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v2
      with:
        name: csv-artifact
        path: ${{ matrix.file_name }}

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: csv-artifact

    - name: Move CSV to repository root
      run: mv ${{ github.workspace }}/csv-artifact/${{ matrix.file_name }} .

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ${{ matrix.file_name }}
        git commit -m "Update ${{ matrix.file_name }}"
        git push origin HEAD
