name: Test Move

on:
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 openpyxl

    - name: Run Python script
      run: python Current_Affairs_Daily_Links_Update.py
      working-directory: .  # Set the working directory to the repository root

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v2
      with:
        name: csv-artifact
        path: daily_current_affairs_links.csv

    - name: Copy artifact to original repository
      uses: actions/checkout@v2
      with:
        repository: TanmayaChaudhary/GitHub_Actions_CI_CD_Testing
        path: artifacts
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Move artifact to repository root
      run: mv artifacts/csv-artifact/daily_current_affairs_links.csv .

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add daily_current_affairs_links.csv
        git commit -m "Update daily_current_affairs_links.csv"
        git push origin main
